### PR TITLE
Updates to the quiz block so it works with WP 6.5

### PR DESCRIPTION
**Pull request by verytwisty**
Hey @luisherranz!

I have recently found the [talk you did at WCEU2023](https://wordpress.tv/2023/10/01/building-interactive-blocks-a-step-by-step-workshop/), and went through the steps of creating your quiz block. The explanations you provided in your talk were very helpful in understanding how the new Interactivity API works - thank you!

However there seem to be quite a few changes to the Interactivity API since you did your talk, and at first it was difficult for me to get your block working, so I have created this PR with the changes needed to make the block work with the new version of the API incase it is helpful to anyone else who is following along with your tutorial.

I think I got everything, except the `selectors` in the PHP set up of the store, as I couldn't find out how to do this with the new version of the Interactivity API.

```
'selectors' => array(
		'wceu2023' => array(
			'toggleText' => __( 'Open menu' ),
			'isActive' => false,
			'inputAnswer' => null
		)
	)
```

I am not sure if this is possible with the new version of the Interactivity API, but let me know how to do it if it is possible!

Thanks

### CODE REVIEW

**Comment by luisherranz** [comment]
This is amazing! Thank you very much, Belinda.

> I think I got everything, except the selectors in the PHP set up of the store, as I couldn't find out how to do this with the new version of the Interactivity API.

Yes, I think the documentation for this part is not very good yet. We need to improve it.

Now, instead of selectors, we use something called derived state. The derived state is part of the `state` property, but it is derived from other parts of the state, either from the state, the context or a combination of both.

We use getters to derive this state, so instead of this:

```js
store("...", {
  selectors: {
    isOpen({ state, context }) {
      return state.selected === context.id;
    },
  },
});
```

you would write this:

```js
store("...", {
  state: {
    get isOpen() {
      const { id } = getContext();
      return state.selected === id;
    },
  },
});
```

The main benefit of using derived state is that you don't have to pass the `store` from one selector to another. They simply work as if they were any other part of the state.

So instead of this:

```js
store("...", {
  selectors: {
    toggleText: (store) => {
      const { selectors, state } = store;
      return selectors.isOpen(store) // you need to execute it and pass the store
        ? state.closeText
        : state.openText;
    },
  },
});
```

you can do this:

```js
store("...", {
  state: {
    get toggleText() {
      return state.isOpen ? state.closeText : state.openText;
    },
  },
});
```

As you can see, `state.isOpen` doesn't need to be manually executed like `selectors.isOpen(store)`. For the consumer, derived state looks exactly like non-derived state.

In the server, the initialization is done the same way as the non-derived state, using the `wp_interactivity_state()` function:

```php
wp_interactivity_state(
	'wceu2023',
	array(
		'isOpen'      => false,
		'toggleText'  => __( 'Open' ),
		// ...
);
```

I hope this makes sense. But if you have any questions, don't hesitate to ask 🙂

---

I have refactored the selectors part. I will wait for you to review it to merge the pull request. But I think everything is ready. 

Again, thank you very much!!

**Review by luisherranz — APPROVED** [review]

**Comment by luisherranz** [comment]
Oh, I should update the README as well before merging this pull request 😅

**Comment by verytwisty** [comment]
Hey @luisherranz Thank you for your explanation of derived state :-D I think that makes sense, I am still getting my head around the Interactivity API! I will download your changes and have a play around, as that's the way I learn the best :-)

Your changes look good to me, so feel free to merge when you are ready!

I have been watching quite a few recordings you and others have made, thank you for taking the time to create those. :-)

**Comment by luisherranz** [comment]
Perfect, thanks again, Belinda!

**Pull request merged**
